"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, CheckCircle2, KeyRound, LockKeyhole, Mail } from "lucide-react";
import { getSupabaseBrowserClient } from "../../lib/supabase/client";

const appUrl = () => process.env.NEXT_PUBLIC_SITE_URL || (typeof window === "undefined" ? "https://milink.ca" : window.location.origin);
function Frame({ children, eyebrow, title, copy }) {
  return <main className="grid min-h-screen place-items-center bg-[#0b0f17] p-4 text-slate-100"><section className="w-full max-w-md rounded-[28px] border border-[#22314e] bg-[#131b2e] p-6 shadow-2xl shadow-black/40 sm:p-9"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#a6e8ed]"><img src="/Logo-Navy1.png" alt="MiLink" className="h-7 w-auto"/><span>MiLink</span></Link><span className="mt-9 grid h-12 w-12 place-items-center rounded-2xl border border-cyan-300/25 bg-cyan-300/10 text-[#a6e8ed]"><KeyRound size={21}/></span><p className="mt-6 text-xs font-bold uppercase tracking-[.14em] text-[#a6e8ed]">{eyebrow}</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-white">{title}</h1><p className="mt-3 text-sm leading-7 text-slate-400">{copy}</p>{children}</section></main>;
}
function Notice({ children, error = false }) { return <div className={`mt-5 flex gap-2 rounded-xl border p-3 text-xs leading-5 ${error ? "border-rose-400/20 bg-rose-400/10 text-rose-100" : "border-cyan-300/20 bg-cyan-300/10 text-slate-200"}`}><CheckCircle2 size={16} className="shrink-0 text-[#a6e8ed]"/>{children}</div>; }

export function ForgotPassword(){
  const [email,setEmail]=useState(""); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState(""); const [error,setError]=useState(false);
  const submit=async event=>{event.preventDefault();const supabase=getSupabaseBrowserClient();if(!supabase){setError(true);setNotice("Password recovery is unavailable until Supabase is configured.");return;}setBusy(true);setNotice("");const {error:requestError}=await supabase.auth.resetPasswordForEmail(email.trim().toLowerCase(),{redirectTo:`${appUrl().replace(/\/$/,"")}/reset-password`});setBusy(false);setError(Boolean(requestError));setNotice(requestError?.message||"Password reset link sent to your email. Please check your inbox.");};
  return <Frame eyebrow="Account recovery" title="Reset your password" copy="Enter the email connected to your MIlink client portal. We’ll send a secure, single-use reset link."><form className="mt-7" onSubmit={submit}><label className="text-xs font-bold text-slate-300">Email address</label><div className="relative mt-2"><Mail size={17} className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-500"/><input required type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="you@company.com" className="w-full rounded-xl border border-slate-700 bg-slate-950/45 py-3.5 pl-11 pr-4 text-sm outline-none transition focus:border-cyan-300"/></div><button disabled={busy} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-sky-300 to-cyan-300 py-3.5 text-sm font-bold text-slate-950 disabled:opacity-50">{busy?"Sending reset link…":"Send reset link"}<ArrowRight size={17}/></button></form>{notice&&<Notice error={error}>{notice}</Notice>}<p className="mt-6 text-center text-sm text-slate-400"><Link href="/portal" className="font-semibold text-[#a6e8ed] hover:text-white">Back to sign in</Link></p></Frame>;
}

export function ResetPassword(){
  const router=useRouter(); const [ready,setReady]=useState(false); const [checking,setChecking]=useState(true); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState(""); const [error,setError]=useState(false);
  useEffect(()=>{let active=true;const supabase=getSupabaseBrowserClient();if(!supabase){if(active){setChecking(false);setError(true);setNotice("Password reset is unavailable until Supabase is configured.");}return undefined;}const redeem=async()=>{const params=new URLSearchParams(window.location.search);const code=params.get("code");if(code){const {error:exchangeError}=await supabase.auth.exchangeCodeForSession(code);if(exchangeError&&active){setError(true);setNotice(exchangeError.message);}}const {data:{session}}=await supabase.auth.getSession();if(active){setReady(Boolean(session));setChecking(false);if(!session&&!notice){setError(true);setNotice("This reset link is invalid or has expired. Request a new one to continue.");}}};redeem();const {data:{subscription}}=supabase.auth.onAuthStateChange((event,session)=>{if(active&&event==="PASSWORD_RECOVERY"&&session){setReady(true);setChecking(false);}});return()=>{active=false;subscription.unsubscribe();};},[]);
  const submit=async event=>{event.preventDefault();if(password.length<8){setError(true);setNotice("Use a password with at least 8 characters.");return;}if(password!==confirm){setError(true);setNotice("Your password confirmation does not match.");return;}setBusy(true);setNotice("");const {error:updateError}=await getSupabaseBrowserClient().auth.updateUser({password});setBusy(false);if(updateError){setError(true);setNotice(updateError.message);return;}setError(false);setNotice("Password updated successfully. Redirecting you to your portal…");window.setTimeout(()=>router.replace("/portal"),900);};
  return <Frame eyebrow="Secure password reset" title="Create a new password" copy="Choose a strong password you do not use elsewhere. This update only affects your MIlink sign-in.">{checking?<p className="mt-8 text-sm text-slate-400">Verifying your secure reset link…</p>:ready?<form className="mt-7" onSubmit={submit}><label className="text-xs font-bold text-slate-300">New password</label><div className="relative mt-2"><LockKeyhole size={17} className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-500"/><input required minLength="8" type="password" value={password} onChange={event=>setPassword(event.target.value)} placeholder="At least 8 characters" className="w-full rounded-xl border border-slate-700 bg-slate-950/45 py-3.5 pl-11 pr-4 text-sm outline-none transition focus:border-cyan-300"/></div><label className="mt-4 block text-xs font-bold text-slate-300">Confirm new password</label><input required minLength="8" type="password" value={confirm} onChange={event=>setConfirm(event.target.value)} placeholder="Repeat your new password" className="mt-2 w-full rounded-xl border border-slate-700 bg-slate-950/45 px-4 py-3.5 text-sm outline-none transition focus:border-cyan-300"/><button disabled={busy} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-sky-300 to-cyan-300 py-3.5 text-sm font-bold text-slate-950 disabled:opacity-50">{busy?"Updating password…":"Update password"}<ArrowRight size={17}/></button></form>:null}{notice&&<Notice error={error}>{notice}</Notice>}{!ready&&!checking&&<p className="mt-6 text-center text-sm text-slate-400"><Link href="/forgot-password" className="font-semibold text-[#a6e8ed] hover:text-white">Request another reset link</Link></p>}</Frame>;
}
